Algoritmo "exerc2"
// Disciplina   : Linguagem e Lógica de Programação
// Descrição   : Informar se o número digitado é ímpar ou par
// Autor(a)    : Heloisa A. de Oliveira
// Data atual  : 08/08/2022
Var
nmr:inteiro
Inicio
// Seção de Comandos
escreval("Digite um número: ")
leia(nmr)

se nmr mod 2 = 0 entao
   escreval("Esse número é par.")
senao
   escreval("Esse número é ímpar.")
fimse

Fimalgoritmo