algoritmo "semnome"
// Função :
// Autor :
// Data : 05/04/2022
// Seção de Declarações 
var
nome:caracter
idade:inteiro
salario,porcentagem,total:real
inicio
// Seção de Comandos
escreval("Digite seu nome: ")
leia(nome)
escreval("Digite sua idade: ")
leia(idade)
escreval("Digite seu salário: ")
leia(salario)

escreval("O seu nome é: ",nome)
escreval("A sua idade é: ",idade)
escreval("O seu salário é: ",salario)

fimalgoritmo
