Algoritmo "tabuada"
// Descrição: Exibir ao usuário tabuada de um número inteiro
// Autor: Heloísa Oliveira
// Data atual: 29/08/2022
Var
// Seção de Declarações das variáveis 
nmr,contador,resultado:inteiro
Inicio
// Seção de Comandos
escreval("Digite um número: ")
leia(nmr)
para contador de 1 ate 10 faca
   resultado <- nmr * contador
   escreval(nmr," x ",contador," = ",resultado)
fimpara


Fimalgoritmo