Algoritmo "exerc1"
// Descrição   : Escrever na tela do número inicial ao final que o usuário escolher
// Autor(a)    : Heloísa
// Data atual  : 15/09/2022
Var
inicial,final,contador:inteiro

Inicio
// Seção de Comandos
escreval("Digite o número inicial: ")
leia(inicial)
escreval("Digite o número final: ")
leia(final)
para contador de inicial ate final faca
     escreval(contador)
fimpara



Fimalgoritmo