Algoritmo "exerc8"
// Descrição   : Ler um valor correspondente ao número de jogadores de um time de vôlei.
// Autor(a)    : Heloisa
// Data atual  : 19/09/2022
Var
time:inteiro
altura,media,soma:real

Inicio
// Seção de Comandos
para time de 1 ate 6 faca
     escreval("Digite a altura: ")
     leia(altura)
     soma <- soma + altura
fimpara

     media <- soma/6
     escreval("A altura média do time é: ",media)

Fimalgoritmo