Algoritmo "exerc3"
// Descrição   : Programa para um professor calcular a media dos alunos
// Autor(a)    : Heloisa
// Data atual  : 16/09/2022
Var
nt1,nt2,alunos:inteiro
média:real

Inicio
// Seção de Comandos
para alunos de 1 ate 10 faca
     escreval("Digite a primeira nota: ")
     leia(nt1)
     escreval("Digite a segunda nota: ")
     leia(nt2)
     media <- (nt1 + nt2)/2
     escreval("A média do aluno" , alunos, " é:", media)
     escreval()
fimpara


Fimalgoritmo