Algoritmo "ex1_matriz"
// Data atual  : 24/10/2022
Var
exmatriz: vetor [1..3, 1..2] de inteiro

Inicio
// Seção de Comandos
exmatriz[1,1] <- 10
exmatriz[1,2] <- 3
exmatriz[2,1] <- 47
exmatriz[2,2] <- 1
exmatriz[3,1] <- 20
exmatriz[3,2] <- 53

escreval(exmatriz[1,1],"  ",exmatriz[1,1])
escreval(exmatriz[2,1],"  ",exmatriz[1,1])
escreval(exmatriz[3,1],"  ",exmatriz[1,1])

Fimalgoritmo