algoritmo "Exercicio_02"
// Função :
// Autor : Heloísa A. de Oliveira
// Data : 25/04/2022
// Seção de Declarações 
var
qtdeminima,qtdemaxima,estoquemedio: real

inicio
// Dados de Entrada
escreval("Digite o valor da Qtde Minima:")
leia(qtdeminima)
escreval("Digite a quantidade da Qtde Maxima:")
leia(qtdemaxima)
//Processamento
estoquemedio<-(qtdeminima+qtdemaxima)/2
//Dados de Saída
escreval("O estoque médio é: ",estoquemedio)

fimalgoritmo
